version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      o: bind
      type: none
      device: /home/abahsine/data/mariadb
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/abahsine/data/wordpress